### ISSUE TITLE
Qemu and freedom-e-sdk has changed,please update.

### ISSUE THREAD

**Issue by alextooter** [twilco/twilco.github.io#6]
Hi,
I am reading your articles from Hacker news, and doing following it.I find rivcv-qemu has merged into qemu mainstream, and freedom-e-sdk example build has a little change,please update follow the latest change.It help later readers.

Thanks.

**Comment by twilco** [comment]
> I find rivcv-qemu has merged into qemu mainstream

Thanks for the callout - fixed with this commit: e1bc4d8ec48ab780de7820027b19a21598457626

Regarding the freedom-e-sdk example instructions, I'm also now getting some errors.  I looked into it a bit but couldn't immediately determine the issue.  Will do some more digging.

**Comment by twilco** [comment]
Okay, I updated the instructions to accurately reflect the new location of the `.elf` file: 6a2335d93099d95c1c2a493a7ce2838260cf2db4

@alextooter, would you mind running through these instructions again and letting me know if it works for you?

**Comment by alextooter** [comment]
> Okay, I updated the instructions to accurately reflect the new location of the `.elf` file: [6a2335d](https://github.com/twilco/twilco.github.io/commit/6a2335d93099d95c1c2a493a7ce2838260cf2db4)
> 
> @alextooter, would you mind running through these instructions again and letting me know if it works for you?

Hi, 
I go through the two articles,most works fine.there are some small typos:
Article 1
"    Move and extract these files into the ~/usys/riscv directory we created earlier."
you delete the create ~/usys/riscv sentence after update qemu section.

Article 2
grep memory riscv64-virt.dst -A 3
typo, should be .dts

Thanks for those articles,I learn a lot things.

**Comment by twilco** [comment]
> you delete the create ~/usys/riscv sentence after update qemu section.

5219cff285dc692aab3cef19be989ec72943139d 

> typo, should be .dts

510cce4f65fb699c00ca24c5fc7492710b4f2fc4

Thanks so much for catching all these mistakes.  I'm glad you got some things out of these articles!  

I'm going to close this out now.  If you have any further problems, feel free to comment again here or create a new issue.  I think I have a good idea of what I want to do for part 3 of this series, so stay tuned within the next ~1-2 months for another post.
